/* Copyright 2005-2026 Mark Dufour and contributors; License GNU GPL version 3 (See LICENSE) */

/* GENERATED by scripts/gen_unicode_db.py from CPython 3.12.3 (unicode 15.0.0) -- do not edit. */

/* shapes of the tables in unicode_db.cpp, see __ss_char_rec in unicode.hpp */

#define __SS_UNICODE_VERSION "15.0.0"
#define __SS_UCD_SHIFT1 8
#define __SS_UCD_SHIFT2 3

extern const __ss_char_record __ss_char_records[314];
extern const __ss_char __ss_char_ext_case[471];
extern const unsigned char __ss_char_index1[4352];
extern const unsigned short __ss_char_index2[5440];
extern const unsigned short __ss_char_index3[5576];
